#!/bin/bash

mypid=$$
args=($@)
runserver=0
port=4567

for file in `find . \! \( -iname ".git*" -prune \) -and ! \( -iname modules -prune \) -and ! \( -iname publish -prune \) -and ! \( -iname bin -prune \) -and ! -iname readme.md -and ! -iname *ds_store -and ! -iname *.swp -and ! -iname base -and -type f`
do
  if [ -f $file ]
  then
    ruby bin/web.watchr.rb -c $file
  fi
done

for ((i=0;i<$#;i++))
do
  case ${args[i]} in
    "-s") runserver=1 ;;
    "-p") port=${args[++i]} ;;
       *) echo "Invalid argument \"${args[i]}\""
  esac
done

if [ "$runserver" -eq "1" ]
then
  node bin/server.js $port &
fi

watchr bin/web.watchr.rb &

trap "kill -TERM -$mypid" SIGINT
while :
do
  sleep 60
done
